server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true
  client:
    #false表示不想注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
logging:
  level:
    #feign以什么级别监控哪个接口
    com.qc.springcloud.service.PaymentFeighService: debug