server:
  port: 8001
spring:
  application:
    name: cloud-payment-hystrix-service
eureka:
  instance:
    instance-id: payment-hystrix
    prefer-ip-address: true
  client:
    #false表示不想注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka